### ISSUE TITLE
Tree height vs. network height

### ISSUE THREAD

**Issue by Qvecell** [nicfel/Recombination-Tutorial#1]
Hi,

What a nice tutorial! Thank you for making it available.
I was wondering if the network height is comparable to the tree height in non-network models, i.e. if it is the time between the most recent common ancestor and the most recent sequence sampled? 
And if so, what is the tree height in this example? I note that it is not assigned an ESS, so what does e.g. 33 mean here?.
I hope you can clarify this :-)

**Comment by nicfel** [comment]
Hi,
In theory, the network height is the analogue to the tree height in the network model. However, the network height can be much more poorly informed than the tree height. The reason is that even after all local trees have reached their root, the network can still go on. This means that it is possible that the height of the network is not informed by any sequence data and is at that point just "sampled from the prior". What you can look at instead is the tree height along the genome. Each position in the genome can have, in theory, it's own local tree and therefore it's own tree height and you can get a tree height estimate for each position.
I hope that helps,
Nicola

**Comment by dynamiskduo** [comment]
Hello, 
thank you for getting back to me :) 
That makes sense - very nice feature to have network height in any case. Do you have any advice on how to look at the tree height along the genome? I am a little confused on how to extract that from the output files from my runs.
Best,
Amanda

**Comment by nicfel** [comment]
Hi Amanda, 
It's currently a "hidden" feature, but I can add it as an app to the next version of the package
Best,
Nicola

**Comment by liamxg** [comment]
Dear @nicfel,

Could I know if you have add it as an app to the current version of the package, thanks.

Best,
Liam
